spring:
  application:
      name: Spring-Boot-gRPC-server



  datasource:
    url: jdbc:mariadb://172.17.0.1:3306/spring-boot-grpc
    username: root
    password: root123
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jdbc:
    template:
      query-timeout: 15s
  grpc:
    server:
      port: 9091


